### ISSUE TITLE
Hundreds of alerts when unzipping Xcode

### ISSUE THREAD

**Issue by ddaddy** [objective-see/BlockBlock#38]
I was installing a new build of Xcode through the Xcodes app when I was suddenly inundated with hundreds of alerts.
Only a reboot would clear them. Maybe there should be a keyboard shortcut on the buttons so I could have dismissed them all.
<img width="2265" alt="Screenshot 2022-03-10 at 10 45 13" src="https://user-images.githubusercontent.com/1425808/157637388-23801e68-0b32-45a0-8724-59c8972cc6de.png">
![Screenshot 2022-03-10 at 10 51 00 copy](https://user-images.githubusercontent.com/1425808/157637535-472eab5b-b9fe-4558-af8f-b76982dfb95e.jpg)

**Comment by luckman212** [comment]
Sorry this isn't helpful, but just had to say—that is the craziest thing I've ever seen 😱

**Comment by ddaddy** [comment]
They just kept coming, fast, across 2 monitors!

**Comment by kylehickinson** [comment]
I had this too, investigated and realized that it's caused by a regex bug in BlockBlock's daemon and will actually alert for any daemon/agent at any deep path that begins with `/Users/{user}/...`

The regex in question: [`^(\/System|\/Users\/.+|)\/Library\/(LaunchDaemons|LaunchAgents)\/.+\.(?i)plist$`](https://github.com/objective-see/BlockBlock/blob/fc1fa5650061d5e2733a9458e86ecc17eaf188bd/Daemon/Daemon/watchList.plist#L24)

This will match something such as `/Users/kyle/Downloads/Library/LaunchDaemons/com.blah.plist` because of the `.+` in that `/Users/` group check. If the goal for BlockBlock is to only check `/Users/{name}/Library/LaunchDaemons` and `/Users/{name}/Library/LaunchAgents` then the `.+` part of that regex should be changed `[^\/]+` instead so that it only checks against a user's home directory.  The regex in question would end up being: `^(\/System|\/Users\/[^\/]+|)\/Library\/(LaunchDaemons|LaunchAgents)\/.+\.(?i)plist$`
